### ISSUE TITLE
EEG Device

### ISSUE THREAD

**Issue by secretenergy** [duanyiqun/DeWave#3]
Good day, thank you for your word/fun in this field. Can you please give a reference for the best over-the-counter EEG device to purchase that is compatible?

**Comment by duanyiqun** [comment]
Hi, thank you so much for your interests. Although limited in this paper, we use the ZuCo dataset as experimental data. However, in our follow-up dataset collection process, we use Neural-Scan Pro+ system as the device. 
We didn't have device comparison yet. This is just for your reference.
